# This file should contain everything to configure the workflow on a global scale.
# In case of sample based data, it should be complemented by a samples.tsv file that contains
# one row per sample. It can be parsed easily via pandas.
pepfile: config/pep/config.yaml

# If testing set true
testing: False
# Paths to the directories holding the fastqs
input: ../incoming/
data: data/
# Path to the sheet holding metadata information
metadata: config/pep/metadata.txt
# Paths to the databases used for classification and taxonomy
database:
  download-path-seq: https://data.qiime2.org/2022.2/common/silva-138-99-seqs.qza
  download-path-tax: https://data.qiime2.org/2022.2/common/silva-138-99-tax.qza
# Forward and reverse primers used for sequencing
primer1: TCGTCGGCAGCGTCAGATGTGTATAAGAGACAG
primer2: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAG
# Relative threshold for the abundance filtering
relative-abundance-filter: 0.001
# Minimum length of a sequence to be retained
min-seq-length: 200
# Minimum quality score for sequences to pass filter
phred-score: 20
# Maximum number of undetermined base calls ("N")
max-ambiguity: 50
# Parameters for plots
metadata-parameters:
  taxa-heatmap-column: swab-site #extract-group-no
  beta-metadata-column: swab-site #extract-group-no
  gneiss-metadata-column: subject #site-name
  rarefaction-max-depth: 500 #400
