# This file should contain everything to configure the workflow on a global scale.
# In case of sample based data, it should be complemented by a samples.tsv file that contains
# one row per sample. It can be parsed easily via pandas.
pepfile: config/pep/config.yaml

# If testing set true
testing: True
# Paths to the directories holding the fastqs
input: ../incoming/
data: data/
# Path to the sheet holding metadata information
metadata: config/pep/metadata.txt
# Paths to the databases used for classification and taxonomy
database:
  download-path-seq: resources/silva-138-99-seqs.qza
  download-path-tax: resources/silva-138-99-tax.qza
# Forward and reverse primers used for sequencing
primer1: TCGTCGGCAGCGTCAGATGTGTATAAGAGACAG
primer2: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAG
# Parameters necessary for filtering
filtering:
  # Relative threshold for the abundance filtering
  relative-abundance-filter: 0.001
  # Minimum length of a sequence to be retained
  min-seq-length: 200
  # Minimum quality score for sequences to pass filter
  phred-score: 20
  # Maximum number of undetermined base calls ("N")
  max-ambiguity: 50
  # The minimum length that a sequence read can be following truncation and still be retained
  min-length-frac: 0.75
  # Increasing this value tends to reduce the number of false positives and to decrease sensitivity.
  chimera-minh: 0.35
# Parameters for plots
metadata-parameters:
  taxa-heatmap-column: swab-site #extract-group-no
  beta-metadata-column: swab-site #extract-group-no
  gneiss-metadata-column: subject #site-name
  # Specify which axes to cluster: ('features', 'samples', 'both', 'none')
  cluster: features
# Parameters for classification
classification:
  # Reject match if percent identity to query is lower
  perc-identity: 0.97
  # Range (1,None), String("all"), Maximum number of hits to keep for each query
  maxaccepts: 1
  # Range(1,None), String("all"), Maximum number of non-matching target sequences to consider before stopping the search
  maxrejects: 1
# Parameters for de-novo clustering with vsearch
clustering:
  #The percent identity at which clustering should be performed
  perc-identity: 0.99
# Parameters set for alpha- and beta-rarefaction
rarefaction:
  # The maximum rarefaction depth. Must be greater than min-depth
  max-depth: 500 #400
  # The total frequency that each sample should be rarefied to prior to computing the diversity metric
  sampling_depth: 100
  # The beta diversity metric to be computed
  metric: euclidean
  # Samples can be clustered with neighbor joining or UPGMA ("nj", "upgma")
  clustering_method: nj
