name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  Cancel-previous-jobs:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - uses: khan/pull-request-workflow-cancel@1.0.0
        with:
          workflows: "main.yml"
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

  Formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Formatting
        uses: github/super-linter@v4.8.7
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_EXCLUDE: CHANGELOG.md
          VALIDATE_SNAKEMAKE_SNAKEFMT: true
          VALIDATE_PYTHON_BLACK: true
          VALIDATE_MARKDOWN: true

  Linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Lint workflow
      uses: snakemake/snakemake-github-action@v1
      with:
        directory: .
        snakefile: workflow/Snakefile
        args: "--lint"

  Testing:
    runs-on: ubuntu-latest
    needs:
      - Linting
      - Formatting
    steps:
    - uses: actions/checkout@v2
    - name: Download test dataset
      run: |
        cd .tests/resources
        wget https://data.qiime2.org/2022.2/common/silva-138-99-seqs.qza
        wget https://data.qiime2.org/2022.2/common/silva-138-99-tax.qza 
        wget https://ftp.ncbi.nlm.nih.gov/refseq/H_sapiens/annotation/GRCh38_latest/refseq_identifiers/GRCh38_latest_genomic.fna.gz
        wget ftp://ftp.ccb.jhu.edu/pub/data/kraken2_dbs/16S_Silva138_20200326.tgz
        gzip -d GRCh38_latest_genomic.fna.gz
        mkdir minikraken2_v2_8GB_201904_UPDATE
        tar -xf 16S_Silva138_20200326.tgz -C minikraken2_v2_8GB_201904_UPDATE/
        cd minikraken2_v2_8GB_201904_UPDATE
        mv 16S_SILVA138_k2db/* .
        rm -r 16S_SILVA138_k2db/
        cd ..
        cd ..
        mkdir -p data/2022-03-17
        curl -sL \
          https://data.qiime2.org/2022.2/tutorials/importing/casava-18-paired-end-demultiplexed.zip > \
          data/2022-03-17/casava-18-paired-end-demultiplexed.zip
        cd data/2022-03-17
        unzip -q casava-18-paired-end-demultiplexed.zip
        rm casava-18-paired-end-demultiplexed.zip
        mv casava-18-paired-end-demultiplexed/* .
        rm -r casava-18-paired-end-demultiplexed/
        rm blank*
        rm PAP*
        rm YUN*
        rm Rep*
        rm BAQ2*
        rm BAQ4*
        ls
    - name: Test workflow (local test data)
      uses: snakemake/snakemake-github-action@v1
      with:
        directory: .tests
        snakefile: workflow/Snakefile
        args: "--use-conda --show-failed-logs -j 2 --conda-cleanup-pkgs"

    - name: Test report
      uses: snakemake/snakemake-github-action@v1
      with:
        directory: .tests
        snakefile: workflow/Snakefile
        args: "--report report.zip"
